### ISSUE TITLE
not working on Pantheon

### ISSUE THREAD

**Issue by jpwitkowski11** [phase2/particle#245] opened 2018-03-01 00:12 UTC
Trying to get it to work in Drupal 8.4.5 with Components module installed. 

Works locally, but when I push and deploy on Pantheon, I get "The website encountered an unexpected error. Please try again later."

Here's my log file:
Twig_Error_Loader: Template "@atoms/_branding.twig" is not defined (Drupal\Core\Template\Loader\ThemeRegistryLoader: Unable to find template "@atoms/_branding.twig" in the Drupal theme registry.) in "themes/particle/apps/drupal/templates/block/block--system-branding-block.html.twig" at line 29. in Twig_Loader_Chain->getCacheKey() (line 129 of /srv/bindings/fb5df1e938a04b7db0f90290ccb8bcec/code/vendor/twig/twig/lib/Twig/Loader/Chain.php).

**Comment by tjheffner** [comment] 2018-03-01 00:31
@jpwitkowski11 can you verify that particle.info.yml has the component-libraries key filled out with the correct namespaces on pantheon?

I have a sneaking suspicion that the twig-namespaces gulp task isn't being run as part of the pantheon deploy process, because it's normally wrapped included in the default pl compile & watch.

**Comment by jpwitkowski11** [comment] 2018-03-01 00:36
Hi Tanner,

Thanks for the prompt response! Been trying to figure this out all day. I've attached the particle.info.yml file, I figured that would be way easier. Let me know what other info you need and I'll send it. Much appreciated!

Best regards,
John



JOHN P. WITKOWSKI
Web Developer
University of California Education Abroad Program
805-893-5370 | eap.ucop.edu
UCEAP Systemwide Office
6950 Hollister Avenue, Suite 200
Goleta CA 93117-5823

________________________________

**Comment by jpwitkowski11** [comment] 2018-03-01 01:35
Btw, if I comment out `{% include "@atoms/_branding.twig" with logo %}` in /apps/drupal/templates/block/block--system-branding-block.html.twig, the theme renders fine in Drupal 8.4.5. HTH!

**Comment by jpwitkowski11** [comment] 2018-03-01 22:00
Thanks for looking into this, Tanner! 

As suggested, I've tried using "@atoms/branding/_branding.twig" and here's the error log that generated:

[01-Mar-2018 20:27:48 UTC] Uncaught PHP Exception Twig_Error_Loader: "Template "@atoms/branding/_branding.twig" is not defined (Drupal\Core\Template\Loader\ThemeRegistryLoader: Unable to find template "@atoms/branding/_branding.twig" in the Drupal theme registry.) in "themes/custom/particle/apps/drupal/templates/block/block--system-branding-block.html.twig" at line 29." at /srv/bindings/e6a878c4f9a34dd5b129d24c24abfe41/code/vendor/twig/twig/lib/Twig/Loader/Chain.php line 129


Next, I deleted 'block--system-branding-block.html.twig' and corresponding function in particle.theme. Here's the error log now:

[01-Mar-2018 21:26:15 UTC] Uncaught PHP Exception Twig_Error_Loader: "Template "@atoms/_breadcrumb.twig" is not defined (Drupal\Core\Template\Loader\ThemeRegistryLoader: Unable to find template "@atoms/_breadcrumb.twig" in the Drupal theme registry.) in "themes/custom/particle/apps/drupal/templates/navigation/breadcrumb.html.twig" at line 12." at /srv/bindings/e6a878c4f9a34dd5b129d24c24abfe41/code/vendor/twig/twig/lib/Twig/Loader/Chain.php line 129

Thanks again for your help!
John

**Comment by tjheffner** [comment] 2018-03-01 22:22
Sorry John, I'm a little confused. You're saying there were no errors during theme render with `{% include "@atoms/_branding.twig" with logo %}` commented out inside of `block--system-branding-block.html.twig`, but with that entire file deleted, there are additional template failures? 

In that first error log, `/_branding.twig` will never be found, there's no namespace for it. `@atoms/branding/_branding.twig` might have a chance.

The fact there are now other template errors is worrying, but points to something funky happening during the Pantheon deploy, perhaps incorrect pathing on some file copies. Doubly so if everything is also rendering as expected locally. I don't know the specifics of your stack or local project structure, but my current project's deploys to Pantheon has a line like this: `rsync -vzhr --delete --exclude 'node_modules/' --exclude '.gitignore' ${WORKSPACE}/src/themes/ ${PANTHEONDIR}/themes/custom/`. That gets our entire theme where Pantheon expects it to be.

**Comment by jpwitkowski11** [comment] 2018-03-02 00:09
Oops, sorry about the confusion - I accidentally posted the wrong one! However, running with "@atoms/branding/_branding.twig" still produced the same error.

I didn't realize you already have Particle functioning in a drupal instance on Pantheon. That makes me think that our issue may be with our pantheon configs. 

Fwiw, I've loaded Particle in both themes/ and in themes/custom with no success. I'll experiment with the rsync command you provided though.
 
Thanks again for your help and time, Tanner!

**Comment by jpwitkowski11** [comment] 2018-03-02 20:51
Fwiw, I installed Particle 9.7 and it is working fine both locally and in pantheon. Not sure that is helpful info.

**Comment by joshuami** [comment] 2018-03-09 00:01
I have seen the same Twig_Error_Loader on a fresh install. When chatting with @illepic about the error, he mentioned that Pantheon might have some rules around their file system that would prevent traversing up two levels to the /source directory for the component-libraries namespace path. 

This got me thinking about what restrictions Pantheon places on the file system. It is recommended that  [/web]/sites/default/files or [/web]/sites/*/files are excluded through .gitignore. (Web is optional depending on whether you've set `web_docroot: true` in your pantheon.yml.) Further, their drops-8 build has a settings.pantheon.php setting that puts the twig cache files in a tmp directory instead of the files directory.

On my local installation of Particle, I get twig cache files in /web/sites/default/files/php/twig/ and it works fine. I tried turning off caching so that the site would just load from the database, but I'm still seeing the problem without caching, which makes me think it is specific to how the namespaced paths in Particle 10.0.0-beta2 on Pantheon.

**Comment by joshuami** [comment] 2018-05-03 00:06
So I'm seeing this same inability to traverse the component paths when we build to CircleCI as well. So I don't think this is specifically a Pantheon issue anymore.

Further, I was able to duplicate the error in a local Lando container after stepping through each instance of the component path and replacing it with a relative path. The result I found is that `includes` work just find but `embeds` are throwing a "is not defined" error.

**Comment by cbrody** [comment] 2018-06-26 03:18
I'm having a similar issue with Drupal 8.5.4 on Acquia Dev Desktop (PHP 7.0.14), npm 5.6.0. Nothing is rendering at all with the particle theme (10.0.0-beta.3):

`The website encountered an unexpected error. Please try again later.</br></br><em class="placeholder">Twig_Error_Loader</em>: Template &quot;@molecules/jumbotron/_jumbotron.twig&quot; is not defined in &quot;themes/particle/apps/drupal/templates/layout/page.html.twig&quot; at line 54`

**Comment by illepic** [comment] 2018-06-26 15:39
@cbrody can you show the contents of your `apps/drupal/particle.info.yml` file? I want to see what your `component-libraries` entries look like.

Something to try in the meantime: Instead of relatives paths within the `component-libraries` section, try absolute pathing from root of the drupal site.

So instead of:

```yml
component-libraries:
  molecules:
    paths:
      - ../../source/_patterns/02-molecules/jumbotron
```

Try:

```yml
component-libraries:
  molecules:
    paths:
      - themes/custom/particle/source/_patterns/02-molecules/jumbotron
```

Careful not to run `npm start` or this will be overwritten while you're testing ;) Essentially, I'm trying to see what Acquia Dev Desktop and Pantheon prefer for pathing to find twig files. 

If you do find that absolute pathing works, then update the `pathRelativeToDir` option in your gulpfile here: https://github.com/phase2/particle/blob/master/gulpfile.js#L53

**Comment by jpwitkowski11** [comment] 2018-06-28 16:22
@cbrody, I don't know if this helps but I have tried installing it at both `themes/` and at `themes/custom/` with no success.

**Comment by cbrody** [comment] 2018-06-29 17:30
I'm unable to get this to work – I'm wondering if I should open a new issue (for Dev Desktop)? The full error is:

```
The website encountered an unexpected error. Please try again later.</br></br><em class="placeholder">Twig_Error_Loader</em>: Template &quot;@molecules/jumbotron/_jumbotron.twig&quot; is not defined in &quot;themes/custom/particle/apps/drupal/templates/layout/page.html.twig&quot; at line 54. in <em class="placeholder">Twig_Loader_Chain-&gt;getCacheKey()</em> (line <em class="placeholder">129</em> of <em class="placeholder">/Users/chris/Sites/devdesktop/landcam-dev/vendor/twig/twig/lib/Twig/Loader/Chain.php</em>). <pre class="backtrace">Drupal\Core\Template\TwigEnvironment-&gt;getTemplateClass(&#039;@molecules/jumbotron/_jumbotron.twig&#039;) (Line: 424)
Twig_Environment-&gt;loadTemplate(&#039;@molecules/jumbotron/_jumbotron.twig&#039;, NULL) (Line: 366)
Twig_Template-&gt;loadTemplate(&#039;@molecules/jumbotron/_jumbotron.twig&#039;, &#039;themes/custom/particle/apps/drupal/templates/layout/page.html.twig&#039;, 54) (Line: 281)
__TwigTemplate_a00c60f0082b12d22ef77836cd0c1faf8854ffc120fedc9cc891264a2fceb4ef_2169222-&gt;__construct(Object) (Line: 487)
Twig_Environment-&gt;loadTemplate(&#039;themes/custom/particle/apps/drupal/templates/layout/page.html.twig&#039;, &#039;2169222&#039;) (Line: 366)
Twig_Template-&gt;loadTemplate(&#039;themes/custom/particle/apps/drupal/templates/layout/page.html.twig&#039;, &#039;themes/custom/particle/apps/drupal/templates/layout/page.html.twig&#039;, 54, &#039;2169222&#039;) (Line: 59)
__TwigTemplate_a00c60f0082b12d22ef77836cd0c1faf8854ffc120fedc9cc891264a2fceb4ef-&gt;doDisplay(Array, Array) (Line: 432)
Twig_Template-&gt;displayWithErrorHandling(Array, Array) (Line: 403)
Twig_Template-&gt;display(Array) (Line: 411)
Twig_Template-&gt;render(Array) (Line: 64)
twig_render_template(&#039;themes/custom/particle/apps/drupal/templates/layout/page.html.twig&#039;, Array) (Line: 384)
Drupal\Core\Theme\ThemeManager-&gt;render(&#039;page&#039;, Array) (Line: 437)
Drupal\Core\Render\Renderer-&gt;doRender(Array, ) (Line: 195)
Drupal\Core\Render\Renderer-&gt;render(Array) (Line: 490)
Drupal\Core\Template\TwigExtension-&gt;escapeFilter(Object, Array, &#039;html&#039;, NULL, 1) (Line: 84)
__TwigTemplate_6d88d7f2894af37516956268666b41309cdd654bb39ad8137d60ec0bba009105-&gt;doDisplay(Array, Array) (Line: 432)
Twig_Template-&gt;displayWithErrorHandling(Array, Array) (Line: 403)
Twig_Template-&gt;display(Array) (Line: 411)
Twig_Template-&gt;render(Array) (Line: 64)
twig_render_template(&#039;core/themes/stable/templates/layout/html.html.twig&#039;, Array) (Line: 384)
Drupal\Core\Theme\ThemeManager-&gt;render(&#039;html&#039;, Array) (Line: 437)
Drupal\Core\Render\Renderer-&gt;doRender(Array, ) (Line: 195)
Drupal\Core\Render\Renderer-&gt;render(Array) (Line: 147)
Drupal\Core\Render\MainContent\HtmlRenderer-&gt;Drupal\Core\Render\MainContent\{closure}() (Line: 582)
Drupal\Core\Render\Renderer-&gt;executeInRenderContext(Object, Object) (Line: 148)
Drupal\Core\Render\MainContent\HtmlRenderer-&gt;renderResponse(Array, Object, Object) (Line: 90)
Drupal\Core\EventSubscriber\MainContentViewSubscriber-&gt;onViewRenderArray(Object, &#039;kernel.view&#039;, Object)
call_user_func(Array, Object, &#039;kernel.view&#039;, Object) (Line: 111)
Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher-&gt;dispatch(&#039;kernel.view&#039;, Object) (Line: 156)
Symfony\Component\HttpKernel\HttpKernel-&gt;handleRaw(Object, 1) (Line: 68)
Symfony\Component\HttpKernel\HttpKernel-&gt;handle(Object, 1, 1) (Line: 57)
Drupal\Core\StackMiddleware\Session-&gt;handle(Object, 1, 1) (Line: 47)
Drupal\Core\StackMiddleware\KernelPreHandle-&gt;handle(Object, 1, 1) (Line: 99)
Drupal\page_cache\StackMiddleware\PageCache-&gt;pass(Object, 1, 1) (Line: 78)
Drupal\page_cache\StackMiddleware\PageCache-&gt;handle(Object, 1, 1) (Line: 47)
Drupal\Core\StackMiddleware\ReverseProxyMiddleware-&gt;handle(Object, 1, 1) (Line: 52)
Drupal\Core\StackMiddleware\NegotiationMiddleware-&gt;handle(Object, 1, 1) (Line: 23)
Stack\StackedHttpKernel-&gt;handle(Object, 1, 1) (Line: 666)
Drupal\Core\DrupalKernel-&gt;handle(Object) (Line: 19)
</pre>
```

**Comment by cbrody** [comment] 2018-07-02 07:59
I've opened a [separate issue](https://github.com/phase2/particle/issues/337) as I'm not sure my problem is necessarily related to this.

**Comment by newoddity** [comment] 2018-09-12 14:32
I found the root cause that was causing this error on my Pantheon install. The default .gitignore from Pantheon includes a section for "# OS generated files #" under that heading it is ignoring 'Icon'. This is cascading down into the theme and /web/themes/custom/particle/source/_patterns/01-atoms/icon to not be committed up to the server. You can verify this by logging in via SFTP to your instance and checking if that icon folder exists. If it does not, look for your .gitignore file that has 'Icon' and delete that bad boy.

**Comment by illepic** [comment] 2018-09-14 17:56
This **shouldn't** be an issue on the v10 full release forward, as the icons folder is now called `svgicons/` since we revamped for Node 10 compatibility.

**Closed by illepic** 2018-09-14 17:56 UTC
Labels: Drupal, bug

**Comment by arun-mps** [comment] 2022-11-02 13:50
Trying to get it to work in Drupal 8.9.20 with Components module installed.

After clear a cache works fine locally and server, but I get  error "The website encountered an unexpected error. Please try again later."

Here's my log file:
Uncaught PHP Exception Twig\\Error\\LoaderError: "Template "@molecules/container/main.twig" is not def
ined in "themes/particle/drupal_theme/apps/drupal-default/drupal_theme/templates/system/page.html.twig" at line 58." at /opt/sites/particle/site-repo/releases/20221102101229/vendor/twig
/twig/src/Loader/ChainLoader.php line 142
