### ISSUE TITLE
Not working on Acquia Dev Desktop

### ISSUE THREAD

**Issue by cbrody** [phase2/particle#337] opened 2018-07-02 07:58 UTC
Hi, I can't get the Drupal 8 theme to work, with either relative or absolute paths in `particle.info.yml`. This is using Particle v10.0.0-beta.3 with Drupal v8.5.4 on Acquia Dev Desktop (v2, PHP v7.0.14), npm v5.6.0 on MacOS (v10.13.5).

```
The website encountered an unexpected error. Please try again later.</br></br><em class="placeholder">Twig_Error_Loader</em>: Template &quot;@molecules/jumbotron/_jumbotron.twig&quot; is not defined in &quot;themes/custom/particle/apps/drupal/templates/layout/page.html.twig&quot; at line 54. in <em class="placeholder">Twig_Loader_Chain-&gt;getCacheKey()</em> (line <em class="placeholder">129</em> of <em class="placeholder">/Users/chris/Sites/devdesktop/landcam-dev/vendor/twig/twig/lib/Twig/Loader/Chain.php</em>). <pre class="backtrace">Drupal\Core\Template\TwigEnvironment-&gt;getTemplateClass(&#039;@molecules/jumbotron/_jumbotron.twig&#039;) (Line: 424)
Twig_Environment-&gt;loadTemplate(&#039;@molecules/jumbotron/_jumbotron.twig&#039;, NULL) (Line: 366)
Twig_Template-&gt;loadTemplate(&#039;@molecules/jumbotron/_jumbotron.twig&#039;, &#039;themes/custom/particle/apps/drupal/templates/layout/page.html.twig&#039;, 54) (Line: 281)
__TwigTemplate_a00c60f0082b12d22ef77836cd0c1faf8854ffc120fedc9cc891264a2fceb4ef_2169222-&gt;__construct(Object) (Line: 487)
Twig_Environment-&gt;loadTemplate(&#039;themes/custom/particle/apps/drupal/templates/layout/page.html.twig&#039;, &#039;2169222&#039;) (Line: 366)
Twig_Template-&gt;loadTemplate(&#039;themes/custom/particle/apps/drupal/templates/layout/page.html.twig&#039;, &#039;themes/custom/particle/apps/drupal/templates/layout/page.html.twig&#039;, 54, &#039;2169222&#039;) (Line: 59)
__TwigTemplate_a00c60f0082b12d22ef77836cd0c1faf8854ffc120fedc9cc891264a2fceb4ef-&gt;doDisplay(Array, Array) (Line: 432)
Twig_Template-&gt;displayWithErrorHandling(Array, Array) (Line: 403)
Twig_Template-&gt;display(Array) (Line: 411)
Twig_Template-&gt;render(Array) (Line: 64)
twig_render_template(&#039;themes/custom/particle/apps/drupal/templates/layout/page.html.twig&#039;, Array) (Line: 384)
Drupal\Core\Theme\ThemeManager-&gt;render(&#039;page&#039;, Array) (Line: 437)
Drupal\Core\Render\Renderer-&gt;doRender(Array, ) (Line: 195)
Drupal\Core\Render\Renderer-&gt;render(Array) (Line: 490)
Drupal\Core\Template\TwigExtension-&gt;escapeFilter(Object, Array, &#039;html&#039;, NULL, 1) (Line: 84)
__TwigTemplate_6d88d7f2894af37516956268666b41309cdd654bb39ad8137d60ec0bba009105-&gt;doDisplay(Array, Array) (Line: 432)
Twig_Template-&gt;displayWithErrorHandling(Array, Array) (Line: 403)
Twig_Template-&gt;display(Array) (Line: 411)
Twig_Template-&gt;render(Array) (Line: 64)
twig_render_template(&#039;core/themes/stable/templates/layout/html.html.twig&#039;, Array) (Line: 384)
Drupal\Core\Theme\ThemeManager-&gt;render(&#039;html&#039;, Array) (Line: 437)
Drupal\Core\Render\Renderer-&gt;doRender(Array, ) (Line: 195)
Drupal\Core\Render\Renderer-&gt;render(Array) (Line: 147)
Drupal\Core\Render\MainContent\HtmlRenderer-&gt;Drupal\Core\Render\MainContent\{closure}() (Line: 582)
Drupal\Core\Render\Renderer-&gt;executeInRenderContext(Object, Object) (Line: 148)
Drupal\Core\Render\MainContent\HtmlRenderer-&gt;renderResponse(Array, Object, Object) (Line: 90)
Drupal\Core\EventSubscriber\MainContentViewSubscriber-&gt;onViewRenderArray(Object, &#039;kernel.view&#039;, Object)
call_user_func(Array, Object, &#039;kernel.view&#039;, Object) (Line: 111)
Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher-&gt;dispatch(&#039;kernel.view&#039;, Object) (Line: 156)
Symfony\Component\HttpKernel\HttpKernel-&gt;handleRaw(Object, 1) (Line: 68)
Symfony\Component\HttpKernel\HttpKernel-&gt;handle(Object, 1, 1) (Line: 57)
Drupal\Core\StackMiddleware\Session-&gt;handle(Object, 1, 1) (Line: 47)
Drupal\Core\StackMiddleware\KernelPreHandle-&gt;handle(Object, 1, 1) (Line: 99)
Drupal\page_cache\StackMiddleware\PageCache-&gt;pass(Object, 1, 1) (Line: 78)
Drupal\page_cache\StackMiddleware\PageCache-&gt;handle(Object, 1, 1) (Line: 47)
Drupal\Core\StackMiddleware\ReverseProxyMiddleware-&gt;handle(Object, 1, 1) (Line: 52)
Drupal\Core\StackMiddleware\NegotiationMiddleware-&gt;handle(Object, 1, 1) (Line: 23)
Stack\StackedHttpKernel-&gt;handle(Object, 1, 1) (Line: 666)
Drupal\Core\DrupalKernel-&gt;handle(Object) (Line: 19)
</pre>
```

**Comment by illepic** [comment] 2018-08-30 15:01
Hi @cbrody , quick question: do you have the Drupal Components Libraries module installed?

https://www.drupal.org/project/components

Once we know that, know that we're looking to solve the pathing issues on Aquia Dev Desktop and Pantheon

**Comment by illepic** [comment] 2018-09-05 15:22
@cbrody we're looking into solving this for the 10.1 (https://github.com/phase2/particle/milestone/3) release. I think this is the same pathing issue that folks on Pantheon are facing.

**Comment by newoddity** [comment] 2018-09-12 14:31
I found the root cause that was causing this error on my Pantheon install. The default .gitignore from Pantheon includes a section for "# OS generated files #" under that heading it is ignoring 'Icon'. This is cascading down into the theme and /web/themes/custom/particle/source/_patterns/01-atoms/icon to not be committed up to the server. You can verify this by logging in via SFTP to your instance and checking if that icon folder exists. If it does not, look for your .gitignore file that has 'Icon' and delete that bad boy.

**Comment by illepic** [comment] 2018-09-12 20:46
@newoddity, **you are an effing rockstar**. This is incredibly helpful. I think I'm just going to rename folders within 10.1 to avoid this entirely.

**Comment by newoddity** [comment] 2018-09-13 12:03
There is also a pull request on Pantheon's Drops 8 (https://github.com/pantheon-systems/drops-8/pull/218), but of course this will not address other environments like Aquia and those that use a template .gitignore.
I'm also going to look further at the Components code and make a pull request to see if it can build the library and only omit the one path and not the entire library so that the error reporting can be more accurate. This has been presenting itself as issues with different atoms as the first twig to request any atom would fail.

**Comment by illepic** [comment] 2018-09-14 04:09
Quick note here that the full v10 release of Particle has already replaced the icon/s folder with "svgicon" when we moved to Node 10 compatible libraries and inline SVGs:

https://github.com/phase2/particle/tree/master/source/_patterns/01-atoms/svgicon

Interested to see if this works on Pantheon/Acquia Dev Desktop.

**Comment by illepic** [comment] 2018-09-26 20:05
Closing here. We haven't heard of any issues since the revamp of the icons systems.

**Closed by illepic** 2018-09-26 20:05 UTC
Labels: Drupal, bug

**Comment by ellyjonez** [comment] 2019-04-09 18:41
Hi - I'm running into this problem on Pantheon with Particle 10.2.1. The error I'm seeing is ```    Twig\Error\LoaderError: Template       
                                         "@molecules/nav/_nav-item.twig" is not 
                                         defined in                             
                                         "themes/particle/apps/drupal/templates 
                                         /navigation/menu--main.html.twig" at  ```  

I have the components module enabled. 

I refactored my source/default folder from an earlier version of Particle, but I don't think anything that affects this got copied over. Part of that was fixing references to icon paths, and I don't have any of the old icon paths kicking around. Any suggestions?

**Comment by newoddity** [comment] 2019-04-09 18:53
This issue has been closed for a while now, would be best to open a new one.
With the information provided, there is little that can be done to look into it.
To see if your current issue is related to the one here, run `git status --ignored` in your project directory and see if any important files are not being committed up.

**Comment by KaseyMK** [comment] 2020-10-15 15:04
Because I found this page by Googling for the same error @ellyjonez mentioned, and because the solution noted by @newoddity pointed me in the right direction, I'll note that I removed 'dist/' from particle/.gitignore in order to make sure all the necessary files - built during local development - made it to our host (Platform), where we don't run builds.
